service: cecytec-reports
runtime: nodejs14 # or another supported version

handlers:
  - url: /(.+\.js)
    static_files: dist/\1
    upload: dist/(.+\.js)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.svg)
    static_files: dist/\1
    upload: dist/(.+\.svg)
    secure: always
    redirect_http_response_code: 301
  
  - url: /(.+\.ttf)
    static_files: dist/\1
    upload: dist/(.+\.ttf)
    secure: always
    redirect_http_response_code: 301

# Deploy app
# gcloud app deploy app.yaml --version=v1 --no-promote --project=cecytec